import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import NavBar from './ui/navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"></link>
        <title>AT Resumé</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <header className='my-5 flex flex-col bg-white text-black items-center leading-none'>
          <div className="italic text-5xl font-bold">
            <h1>Antoine Tabet </h1>
          </div>
          <div className="flex flex-row text-xl">
            <div className="flex items-center mx-2">
              <p>Toronto, Ontario, Canada <i className="fas fa-map-marker-alt"></i>
              </p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="tel:+14162540034">+1 (416) 254-0034 <i className="fas fa-phone"></i>
              </Link></p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="mailto:antoine.tabet@mail.utoronto.ca">antoine.tabet@mail.utoronto.ca <i
                className="fas fa-envelope"></i>
              </Link></p>
            </div>
            <div className="flex items-center mx-2">
              <p>
                <Link className='hover:text-violet-600' href="https://www.linkedin.com/in/antoinetabetuoft/" target="_blank">LinkedIn <i
                  className="fab fa-linkedin"></i></Link>
              </p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="https://github.com/tabetant" target="_blank">GitHub <i className="fab fa-github"></i>
              </Link>
              </p>
            </div>
          </div>
        </header>
        <div>
          <NavBar />
        </div>
        <div className='container mx-auto px-4'>
          {children}
        </div>
        <footer className='text-black text-center mt-5'>
          <h2>Socials:</h2>
          <ul>
            <li>
              <Link className='hover:text-violet-600' href="https://www.instagram.com/antoun8?igsh=Y3Jzc3IwZXlwbzZz&utm_source=qr"
                target="_blank">Instagram <i className="fab fa-instagram"></i></Link>
            </li>
            <li>
              <Link className='hover:text-violet-600' href="https://snapchat.com/t/o8C7U8Uy" target="_blank">Snapchat <i
                className="fab fa-snapchat"></i></Link>
            </li>
          </ul>
        </footer>
      </body>
    </html >
  );
}
