import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import NavBar from './ui/navbar'
import { exile } from '@/app/ui/fonts';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"></link>
        <title>AT Resumé</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <header className='my-5 flex flex-col bg-white text-black items-center leading-none'>
          <div className={`${exile.className} text-5xl font-bold`}>
            <h1>Antoine Tabet </h1>
          </div>
          <div className="flex flex-row text-xl">
            <div className="flex items-center mx-2">
              <p>Toronto, Ontario, Canada <i className="fas fa-map-marker-alt"></i>
              </p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="tel:+14162540034">+1 (416) 254-0034 <i className="fas fa-phone"></i>
              </Link></p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="mailto:antoine.tabet@mail.utoronto.ca">antoine.tabet@mail.utoronto.ca <i
                className="fas fa-envelope"></i>
              </Link></p>
            </div>
            <div className="flex items-center mx-2">
              <p>
                <Link className='hover:text-violet-600' href="https://www.linkedin.com/in/antoinetabetuoft/" target="_blank">LinkedIn <i
                  className="fab fa-linkedin"></i></Link>
              </p>
            </div>
            <div className="flex items-center mx-2">
              <p><Link className='hover:text-violet-600' href="https://github.com/tabetant" target="_blank">GitHub <i className="fab fa-github"></i>
              </Link>
              </p>
            </div>
          </div>
        </header>
        <div>
          <NavBar />
        </div>
        <div className='container mx-auto px-4'>
          {children}
        </div>
        <footer className="w-full bg-gray-50 py-8 mt-10 border-t border-gray-200">
          <div className="max-w-screen-xl mx-auto px-6 flex flex-col items-center space-y-4">
            <h2 className="text-3xl font-semibold text-gray-800">Socials</h2>
            <ul className="flex flex-wrap justify-center gap-6 text-lg text-gray-600">
              <li>
                <Link
                  href="https://www.instagram.com/antoun8?igsh=Y3Jzc3IwZXlwbzZz&utm_source=qr"
                  target="_blank"
                  className="hover:text-violet-600 transition"
                >
                  <i className="fab fa-instagram mr-2"></i>Instagram
                </Link>
              </li>
              <li>
                <Link
                  href="https://snapchat.com/t/o8C7U8Uy"
                  target="_blank"
                  className="hover:text-violet-600 transition"
                >
                  <i className="fab fa-snapchat mr-2"></i>Snapchat
                </Link>
              </li>
            </ul>
            <p className="text-sm text-gray-400">© {new Date().getFullYear()} Antoine Tabet. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html >
  );
}
